# Generated by Django 6.0.6 on 2026-06-28 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("developers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("template", "Website Template"),
                            ("saas", "SaaS Starter"),
                            ("plugin", "Plugin / Extension"),
                            ("script", "Script / Tool"),
                            ("mobile", "Mobile App"),
                            ("api", "API / Service"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tech_stack", models.CharField(blank=True, max_length=300)),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("demo_url", models.URLField(blank=True)),
                (
                    "repo_url",
                    models.URLField(blank=True, help_text="Private until purchased"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "developer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="developers.developerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductPurchase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=12)),
                ("mpesa_ref", models.CharField(blank=True, max_length=100)),
                ("stripe_ref", models.CharField(blank=True, max_length=100)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "download_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="store.softwareproduct",
                    ),
                ),
            ],
        ),
    ]
