# Generated by Django 6.0.6 on 2026-06-28 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("bid_received", "New bid on your project"),
                            ("bid_accepted", "Your bid was accepted"),
                            ("bid_rejected", "Your bid was rejected"),
                            ("milestone_submitted", "Deliverable submitted"),
                            ("milestone_approved", "Milestone approved"),
                            ("payment_released", "Payment released"),
                            ("message", "New message"),
                            ("review", "New review"),
                            ("subscription", "Subscription update"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=300)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
